name: Build image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build image
    runs-on: macos-14
    steps:
    - name: prepare dependencies
      run:
        brew install make openssl;
        brew tap messense/macos-cross-toolchains;
        brew install aarch64-unknown-linux-gnu;
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: make
      run: ./limacos build
    - uses: actions/upload-artifact@v4
      with:
        name: Image
        path: linux/arch/arm64/boot/Image
        if-no-files-found: error
